version: '3.4'

services:
  primaryservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+:80;http://+:9002
      - ASPNETCORE_MANAGEMENTPORT=9002    # If you want a separate port for healthchecks
      - ASPNETCORE_CONNECTIONSTRING=Server=primaryservice-db;Database=master;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;
    ports:
      - "45024:80"
      - "9002:9002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  primaryservice.database:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"    # Important: In a production environment you should remove the external port
      
  secondaryservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+:80;http://+:9003
      - ASPNETCORE_MANAGEMENTPORT=9003    # If you want a separate port for healthchecks
      - ASPNETCORE_CONNECTIONSTRING=Server=secondaryservice-db;Database=master;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;
    ports:
      - "45025:80"
      - "9003:9003"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  secondaryservice.database:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1434:1434"    # Important: In a production environment you should remove the external port
